version: "3.5"

services:

  app:
    build: .
    container_name: test-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/info || exit"
      start_period: 10s
